name: Backend CI

on:
  pull_request:
    paths:
      - "/**"

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        working-directory: ./
      - name: Run Tests
        run: npm test:ci
        working-directory: ./
